#!/usr/bin/env bash
# chezmoi: run once — prints setup completion summary

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                   Setup complete!                           ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  ✓  Xcode CLI tools                                        ║"
echo "║  ✓  Homebrew + all packages (Brewfile)                     ║"
echo "║  ✓  Dotfiles symlinked (~/.zshrc, ~/.gitconfig, etc.)      ║"
echo "║  ✓  VSCode settings copied                                  ║"
echo "║  ✓  aicommit2 installed                                     ║"
echo "║  ✓  krew plugins: neat, resource-capacity, who-can         ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Remaining manual steps:                                    ║"
echo "║                                                              ║"
echo "║  1. Reload shell:   source ~/.zshrc                        ║"
echo "║  2. GitHub CLI:     gh auth login                          ║"
echo "║  3. Atuin sync:     atuin login                            ║"
echo "║  4. SSH key:        ssh-keygen -t ed25519 -C \"you@example\" ║"
echo "║  5. AWS auth:       aws configure                           ║"
echo "║  6. Git email:      git config --global user.email <email> ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
